# Generated by Django 4.0.6 on 2022-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
