# Generated by Django 4.0.6 on 2022-07-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_post_comment_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
    ]
