# Generated by Django 4.0.6 on 2022-07-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_article_comment_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
    ]
